---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: jenkins
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: jenkins
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.9.4-1"
    appversion.kubeaddons.mesosphere.io/jenkins: "1.9.4"
    values.chart.helm.kubeaddons.mesosphere.io/jenkins: "https://raw.githubusercontent.com/kaiwalyajoshi/mesosphere-helm-charts/kjoshi/kubeaddons-jenkins/stable/jenkins/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.16.3
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/provides: traefik
  chartReference:
    chart: stable/jenkins
    version: 1.9.4
    values: |
      ---
      master:
        useSecurity: false
        installPlugins:
          - prometheus:2.0.6
          - kubernetes:1.18.2
          - workflow-job:2.33
          - workflow-aggregator:2.6
          - credentials-binding:1.19
          - git:3.11.0
        csrf:
          defaultCrumbIssuer:
            enabled: false
            proxyCompatability: false
        prometheus:
          enabled: true
        serviceMonitorNamespace: "kubeaddons"
        serviceMonitorAdditionalLabels:
          app: jenkins
          release: prometheus-kubeaddons
        serviceType: "ClusterIP"
        jenkinsUriPrefix: "/jenkins"
        ingress:
          enabled: true
        path: /jenkins
        annotations:
          kubernetes.io/ingress.class: traefik
