---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: zookeeper
  namespace: kubeaddons
  labels:
    kubeaddons.mesosphere.io/name: zookeeper
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.1.0-1"
    appversion.kubeaddons.mesosphere.io/zookeeper: "0.2.0"
spec:
  kubernetes:
    minSupportedVersion: v1.16.0
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: kudo
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  kudoReference:
    package: zookeeper
    repo: https://kudo-repository.storage.googleapis.com/
    version: 0.2.0
