---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: zookeeper
  labels:
    kubeaddons.mesosphere.io/name: zookeeper
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/certification: "Certified, Supported"
    catalog.kubeaddons.mesosphere.io/addon-revision: "3.4.14-2"
    appversion.kubeaddons.mesosphere.io/zookeeper: "3.4.14"
spec:
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  kudoReference:
    package: zookeeper
    repo: https://kudo-repository.storage.googleapis.com/0.10.0
    version: 0.3.0
