apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: jenkins
  labels:
    kubeaddons.mesosphere.io/name: jenkins
  annotations:
    catalog.kubeaddons.mesosphere.io/certification: '["certified"]'
    catalog.kubeaddons.mesosphere.io/addon-revision: "2.303.3-1"
    appversion.kubeaddons.mesosphere.io/jenkins: "2.303.3"
    values.chart.helm.kubeaddons.mesosphere.io/jenkins: "https://raw.githubusercontent.com/helm/charts/f4f301a/stable/jenkins/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.16.3
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  chartReference:
    chart: jenkins
    repo: https://charts.jenkins.io
    version: 3.8.8
    values: |
      ---
      master:
        useSecurity: false
        installPlugins:
          - prometheus:2.0.6
          - kubernetes:1.18.2
          - workflow-job:2.33
          - workflow-aggregator:2.6
          - credentials-binding:1.19
          - git:3.11.0
        csrf:
          defaultCrumbIssuer:
            enabled: false
            proxyCompatability: false
        serviceType: "ClusterIP"
        jenkinsUriPrefix: "/jenkins"
        ingress:
          enabled: true
          path: /jenkins
          annotations:
            kubernetes.io/ingress.class: traefik
