apiVersion: kubeaddons.mesosphere.io/v1beta2
kind: Addon
metadata:
  name: elasticsearch-exporter
  labels:
    kubeaddons.mesosphere.io/name: elasticsearch-exporter
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/certification: '["certified"]'
    catalog.kubeaddons.mesosphere.io/addon-revision: "1.5.0-1"
    appversion.kubeaddons.mesosphere.io/elasticsearch-exporter: "1.5.0"
    values.chart.helm.kubeaddons.mesosphere.io/elasticsearch-exporter: "https://raw.githubusercontent.com/mesosphere/charts/02880c3/stable/elasticsearch-exporter/values.yaml"
spec:
  kubernetes:
    minSupportedVersion: v1.15.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: gcp
      enabled: true
    - name: docker
      enabled: false
    - name: none
      enabled: true
  requires:
    - matchLabels:
        kubeaddons.mesosphere.io/name: elasticsearch-oss
  chartReference:
    chart: prometheus-elasticsearch-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 4.15.0
    values: |
      ---
      #fullnameOverride: ""
      #nameOverride: ""
      es:
        uri: http://elasticsearch-oss-client:9200
      service:
        labels:
          servicemonitor.kubeaddons.mesosphere.io/path: "metrics"
        metricsPort:
          name: metrics
