---
apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: Addon
metadata:
  name: cassandra
  labels:
    kubeaddons.mesosphere.io/name: cassandra
    kubeaddons.mesosphere.io/hack-requires-defaultstorageclass: "true"
  annotations:
    catalog.kubeaddons.mesosphere.io/addon-revision: "0.1.0-1"
    appversion.kubeaddons.mesosphere.io/cassandra: "0.1.2"
    stage.kubeaddons.io/cassandra: Beta
spec:
  kubernetes:
    minSupportedVersion: v1.16.0
  cloudProvider:
    - name: aws
      enabled: true
    - name: azure
      enabled: true
    - name: docker
      enabled: true
    - name: none
      enabled: true
  kudoReference:
    package: cassandra
    repo: https://kudo-repository.storage.googleapis.com/0.10.0
    version: 0.1.2
    appVersion: 3.11.5
